[toolchain]
anchor_version = "1.2.1"

[workspace]
members = ["contract/counter", "contract/oracle", "contract/pyth-pay-usd"]

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[programs.localnet]
my_counter = "53fUjUVA7GCU2r279UD43NjCXRaR2dnocwwDZQKvAf1w"
my_oracle = "CR651qrjHq9v18JC9qqzHZcFThFTa9dycHXofxxFcotn"
pyth_program = "SwaoHArzRjzX16rctWM6EdeFBWHbitv91H3QuwELeyd"
