/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/OeNiXkjUPgW
 */
import { Button } from "@/components/ui/button"
import { WalletButton } from "./wallet-button"

export function Header() {
  return (
    <section className="w-full py-12 px-8 md:px-12 lg:px-24 xl:px-32 mx-auto bg-gradient-to-r from-purple-400 via-pink-500 to-red-500 relative">
      <div className="absolute right-0 top-0 mt-8 mr-8 z-50 md:block hidden">
        <div>
          <WalletButton />
        </div>
      </div>
      <div className="container px-4 md:px-6">
        <div className="grid gap-6 lg:grid-cols-[1fr_400px] lg:gap-12 xl:grid-cols-[1fr_600px]">
          <div className="flex flex-col justify-center space-y-4">
            <div className="space-y-4">
              <h1 className="text-4xl font-bold tracking-tighter text-white sm:text-5xl xl:text-6xl">
                EXPLORE MY DAPPS ON SOLANA
              </h1>
              <p className="max-w-[600px] text-gray-200 md:text-xl">
                Learn wallet connections, transfers, counters, and oracle data with small Solana examples.
              </p>
              <p className="max-w-[600px] text-gray-200 md:text-xl">
                The source code of all the projects can be found on {' '}
                <a href="https://github.com/SebastianBoehler/solana-dapp-learning" target="_blank" rel="noopener noreferrer" className="underline">
                  GitHub
                </a>.
              </p>
            </div>
            <div>
              <p className="text-sm py-4 text-white">Wallet actions use Devnet</p>
              <nav className="flex gap-4 text-white underline" aria-label="Examples">
                <a href="/">Examples</a><a href="/oracle">Oracle</a>
                <a href="/sendUsd">USD payment</a><a href="/arbitrage">Jupiter quotes</a>
              </nav>
            </div>
            <div className="md:hidden block">
              <WalletButton />
            </div>
          </div>
        </div>
      </div>
    </section>
  )
}
